baseURL = "https://debimate.jp/"
locale = "ja-jp"
title = "Debimate"
theme = "PaperMod"
enableRobotsTXT = true
hasCJKLanguage = true
ignoreLogs = ['warning-goldmark-raw-html']
env = "production"
images = ["images/icon.jpg"]
publishDir = "public"

[services]
  [services.googleAnalytics]
    id = "G-CT6HRDERYM"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[pagination]
  pagerSize = 60
