#!/usr/bin/env python3
"""移行前 URL 向けのリダイレクト HTML を static/ 配下へ生成する。

記事の旧 URL は Hugo の aliases（scripts/ensure_post_aliases.py が付与）で
賄えるが、タクソノミー・固定ページ・削除済み記事の旧 URL は記事に紐付かない。
それらを scripts/legacy_redirects.tsv に列挙し、GitHub Pages でも動く
meta refresh のスタブとして吐き出す。
"""

from __future__ import annotations

import argparse
import html
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
TABLE_PATH = REPO_ROOT / "scripts" / "legacy_redirects.tsv"
OUTPUT_ROOT = REPO_ROOT / "static"
BASE_URL = "https://debimate.jp"
STUB_MARKER = "<!-- generated by scripts/gen_legacy_redirects.py -->"


def load_table() -> list[tuple[str, str]]:
    rules: list[tuple[str, str]] = []
    for lineno, line in enumerate(TABLE_PATH.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 2:
            raise ValueError(f"{TABLE_PATH.name}:{lineno}: expected '<source>\\t<target>'")
        source, target = (part.strip() for part in parts)
        if not source.startswith("/") or not target.startswith("/"):
            raise ValueError(f"{TABLE_PATH.name}:{lineno}: paths must start with '/'")
        rules.append((source, target))
    return rules


def render_stub(target: str) -> str:
    url = html.escape(f"{BASE_URL}{target}")
    return (
        "<!DOCTYPE html>\n"
        f'<html lang="ja">\n'
        "  <head>\n"
        '    <meta charset="utf-8">\n'
        f'    <title>{url}</title>\n'
        f'    <link rel="canonical" href="{url}">\n'
        '    <meta name="robots" content="noindex">\n'
        f'    <meta http-equiv="refresh" content="0; url={url}">\n'
        "  </head>\n"
        f"  <body>{STUB_MARKER}</body>\n"
        "</html>\n"
    )


def clean_previous() -> None:
    """前回生成分だけを消す。手書きの static/ ファイルには触れない。

    表から消したルールのスタブも確実に片付くよう、目印を持つファイルを
    static/ 全体から探す。空になったディレクトリも畳む。
    """
    for path in OUTPUT_ROOT.rglob("index.html"):
        if STUB_MARKER in path.read_text(encoding="utf-8"):
            path.unlink()

    for path in sorted(OUTPUT_ROOT.rglob("*"), key=lambda p: len(p.parts), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit non-zero when the output is stale")
    args = parser.parse_args()

    rules = load_table()
    if args.check:
        outdated = [
            source
            for source, target in rules
            if not (path := OUTPUT_ROOT / source.strip("/") / "index.html").is_file()
            or path.read_text(encoding="utf-8") != render_stub(target)
        ]
        if outdated:
            print(f"{len(outdated)} redirects would be regenerated")
            return 1
        print("redirects are up to date")
        return 0

    clean_previous()
    for source, target in rules:
        destination = OUTPUT_ROOT / source.strip("/") / "index.html"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(render_stub(target), encoding="utf-8")

    print(f"generated {len(rules)} redirects under {OUTPUT_ROOT.relative_to(REPO_ROOT)}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
